project:
  type: website
  output-dir: _site

website:
  title: "Multi-Metabolite Signatures of exposure"
  site-url: "https://nestanyol.github.io/MMS/"
  repo-url: "https://github.com/nestanyol/MMS"
  repo-actions: [edit, issue]
  navbar: false

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Overview"
        contents:
          - notebooks/intro.qmd
          - notebooks/methods.qmd
      - section: "Analytical workflow"
        contents:
          - notebooks/workflow.qmd
          - notebooks/feature_selection.qmd
          - notebooks/feature_selection.qmd
          # - notebooks/02_preprocessing.qmd
          # - notebooks/03_feature_engineering.qmd
          # - notebooks/04_modeling.qmd
          # - notebooks/05_validation.qmd
          # - notebooks/06_interpretation.qmd
      - section: "Reports"
        contents:
          - reports/final_report.qmd
          # - reports/appendix.qmd

format:
  html:
    theme:
      - cosmo
      - styles/custom.scss
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    highlight-style: github
    include-in-header:
      - text: |
          <meta name="viewport" content="width=device-width, initial-scale=1" />

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

# bibliography: references/references.bib
# # csl: references/csl.csl
